"""Curated model capability registry.

Populated from a multi-agent web research pass (2026-07-26) across Anthropic
Claude, OpenAI, Google Gemini, and open-weight (DeepSeek/Qwen/gpt-oss/Kimi)
families -- see docs/model-matrix-research.md for full source citations and
research notes per model. Extend this list as new models ship; it's plain
data, no code changes needed elsewhere.

Scores (1-5) reflect researched benchmark evidence where available, with
gaps explicitly noted in one_line_summary rather than guessed. Known-retired
models are kept (not deleted) because a source agent migration may still
reference their id -- the resolver needs to recognize them even though they
can no longer be a *target*.
"""

from __future__ import annotations

from agent_liftoff.model_matrix.types import CostTier, ModelProfile

PROFILE_REGISTRY: list[ModelProfile] = [
    # ======================================================================
    # Anthropic Claude
    # ======================================================================
    ModelProfile(
        model_family="Claude Fable 5",
        known_ids=["claude-fable-5"],
        provider="anthropic",
        release_date="2026-06-09",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["long-horizon-agentic", "always-on-thinking", "long-context", "memory-tool", "parallel-subagents"],
        one_line_summary="Anthropic's most capable widely-released model, built for the hardest reasoning and longest-horizon autonomous agent work (GPQA Diamond 93.2%, SWE-bench Verified ~95%).",
        sources=["https://platform.claude.com/docs/en/about-claude/models/introducing-claude-fable-5.md"],
    ),
    ModelProfile(
        model_family="Claude Opus 5",
        known_ids=["claude-opus-5"],
        provider="anthropic",
        release_date="2026-07-24",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["agentic-coding", "computer-use", "cost-effective-frontier", "tool-use"],
        one_line_summary="Anthropic's newest default agentic-coding/computer-use workhorse -- near-Fable-5 capability at half the price (SWE-bench Verified 96.0%, OSWorld 70.6%).",
        sources=["https://www.anthropic.com/news/claude-opus-5"],
    ),
    ModelProfile(
        model_family="Claude Opus 4.8",
        known_ids=["claude-opus-4-8"],
        provider="anthropic",
        release_date="2026-05-27",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["long-horizon-agentic", "computer-use", "coding"],
        one_line_summary="Best-in-class OSWorld computer-use (83.4%) and SWE-bench Pro (69.2%) at launch; now a legacy tier vs. Opus 5/Fable 5.",
        sources=["https://www.vellum.ai/blog/claude-opus-4-8-benchmarks-explained"],
    ),
    ModelProfile(
        model_family="Claude Opus 4.7",
        known_ids=["claude-opus-4-7"],
        provider="anthropic",
        release_date="2026-04-16",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["high-res-vision", "tool-use-reliability", "task-budgets"],
        one_line_summary="Introduced Task Budgets and high-res vision; led its generation on MCP-Atlas tool-calling reliability (77.3%).",
        sources=["https://www.vellum.ai/blog/claude-opus-4-7-benchmarks-explained"],
    ),
    ModelProfile(
        model_family="Claude Opus 4.6",
        known_ids=["claude-opus-4-6"],
        provider="anthropic",
        release_date="2026-02-05",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["long-context (first 1M Opus)", "reasoning-jump"],
        one_line_summary="First Opus with a 1M-token context window; large ARC-AGI-2 jump (68.8%) over Opus 4.5 while coding held flat.",
        sources=["https://www.vellum.ai/blog/claude-opus-4-6-benchmarks"],
    ),
    ModelProfile(
        model_family="Claude Sonnet 5",
        known_ids=["claude-sonnet-5"],
        provider="anthropic",
        release_date="2026-06-30",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic-coding", "cost-effective-near-frontier", "xhigh-effort"],
        one_line_summary="Best speed/intelligence balance in the current lineup -- first Claude model to cross 80% on SWE-bench Verified (82.1%), Terminal-Bench 76.1%.",
        sources=["https://www.marktechpost.com/2026/07/13/anthropic-claude-sonnet-5-vs-sonnet-4-6-vs-opus-4-8-agentic-coding-benchmarks-api-pricing-and-cost-performance-tradeoffs-compared/"],
    ),
    ModelProfile(
        model_family="Claude Sonnet 4.6",
        known_ids=["claude-sonnet-4-6"],
        provider="anthropic",
        release_date="2026-02-17",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["near-flagship-value", "long-context"],
        one_line_summary="Matched then-flagship Opus 4.6 on office/financial-analysis tasks at a fifth of the price; since eclipsed by Sonnet 5's agentic-coding jump.",
        sources=["https://www.365i.co.uk/news/2026/02/18/claude-sonnet-4-6-release-near-flagship-ai/"],
    ),
    ModelProfile(
        model_family="Claude Sonnet 4.5",
        known_ids=["claude-sonnet-4-5", "claude-sonnet-4-5-20250929"],
        provider="anthropic",
        release_date="2025-09-29",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["tau-bench-leader", "agentic-coding", "extended-thinking"],
        one_line_summary="Workhorse Sonnet-tier model with strong, well-documented tau-bench (Telecom 98.0%) and OSWorld (61.4%) scores -- a solid balanced-migration baseline.",
        sources=["https://caylent.com/blog/claude-sonnet-4-5-highest-scoring-claude-model-yet-on-swe-bench"],
    ),
    ModelProfile(
        model_family="Claude Haiku 4.5",
        known_ids=["claude-haiku-4-5", "claude-haiku-4-5-20251001"],
        provider="anthropic",
        release_date="2025-10-15",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "fast", "extended-thinking", "coding-capable-for-tier"],
        one_line_summary="Fastest/cheapest current Claude model with near-frontier intelligence (SWE-bench Verified 73.3%) -- best cost/performance ratio for high-volume agentic tasks.",
        sources=["https://www.anthropic.com/news/claude-haiku-4-5"],
    ),
    ModelProfile(
        model_family="Claude Opus 4.5",
        known_ids=["claude-opus-4-5", "claude-opus-4-5-20251101"],
        provider="anthropic",
        release_date="2025-11-01",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["coding-leader-at-launch", "extended-thinking"],
        one_line_summary="Best model for software-engineering tasks at its Nov 2025 launch (SWE-bench Verified 80.9%); agentic-tool-use score lower-confidence (no direct benchmark found).",
        sources=["https://www.vellum.ai/blog/claude-opus-4-5-benchmarks"],
    ),
    ModelProfile(
        model_family="Claude Opus 4.1",
        known_ids=["claude-opus-4-1", "claude-opus-4-1-20250805"],
        provider="anthropic",
        release_date="2025-08-05",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["legacy"],
        one_line_summary="Deprecated Opus 4-generation model, retiring 2026-08-05 -- remap any source reference directly to Claude Opus 5.",
        sources=["https://platform.claude.com/docs/en/about-claude/model-deprecations"],
    ),
    ModelProfile(
        model_family="Claude Sonnet 3.7",
        known_ids=["claude-3-7-sonnet-20250219"],
        provider="anthropic",
        release_date="2025-02-24",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=2,
        coding_strength=2,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["legacy"],
        one_line_summary="Retired February 2026 -- the API now hard-errors on this id; remap directly to Claude Sonnet 5.",
        sources=["https://platform.claude.com/docs/en/about-claude/model-deprecations"],
    ),
    ModelProfile(
        model_family="Claude Haiku 3.5",
        known_ids=["claude-3-5-haiku-20241022"],
        provider="anthropic",
        release_date="2024-10-22",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=1,
        coding_strength=2,
        agentic_tool_use_strength=1,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["legacy", "cheap"],
        one_line_summary="Retired February 2026 -- the API now hard-errors on this id; remap directly to Claude Haiku 4.5.",
        sources=["https://platform.claude.com/docs/en/about-claude/model-deprecations"],
    ),

    # ======================================================================
    # OpenAI
    # ======================================================================
    ModelProfile(
        model_family="GPT-5.6 Sol",
        known_ids=["gpt-5.6-sol"],
        provider="openai",
        release_date="2026-07-09",
        context_window=1_050_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["frontier-reasoning", "long-context", "computer-use", "coding"],
        one_line_summary="OpenAI's current flagship for complex professional/research/coding/agentic work; GPQA Diamond 94.6%, native computer-use and web/file search tools.",
        sources=["https://kingy.ai/blog/gpt-5-6-sol-terra-luna-benchmarks-specs/"],
    ),
    ModelProfile(
        model_family="GPT-5.6 Terra",
        known_ids=["gpt-5.6-terra"],
        provider="openai",
        release_date="2026-07-09",
        context_window=1_050_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["balanced-cost-intelligence", "computer-use", "agentic-workflows"],
        one_line_summary="The 'balances intelligence and cost' mid-tier of the current GPT-5.6 generation, aimed at general-purpose agent deployments.",
        sources=["https://kingy.ai/blog/gpt-5-6-sol-terra-luna-benchmarks-specs/"],
    ),
    ModelProfile(
        model_family="GPT-5.6 Luna",
        known_ids=["gpt-5.6-luna"],
        provider="openai",
        release_date="2026-07-09",
        context_window=1_050_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "fast", "full-tool-use-api-surface"],
        one_line_summary="OpenAI's cost-optimized current-gen tier -- cheapest of the Sol/Terra/Luna trio while keeping the same tool/agent API surface.",
        sources=["https://kingy.ai/blog/gpt-5-6-sol-terra-luna-benchmarks-specs/"],
    ),
    ModelProfile(
        model_family="GPT-5.3-Codex",
        known_ids=["gpt-5.3-codex", "gpt-5.3-codex-spark"],
        provider="openai",
        release_date="2026-02-05",
        context_window=400_000,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["coding", "terminal-agentic-coding", "repo-level-tasks", "debugging"],
        one_line_summary="OpenAI's dedicated coding-agent line -- SOTA on SWE-bench Pro/Terminal-Bench 2.0 (77.3%) at release; not tuned for general chat.",
        sources=["https://en.wikipedia.org/wiki/GPT-5.3-Codex"],
    ),
    ModelProfile(
        model_family="GPT-5.1",
        known_ids=["gpt-5.1", "gpt-5.1-thinking", "gpt-5.1-instant", "gpt-5.1-chat-latest", "gpt-5.1-pro"],
        provider="openai",
        release_date="2025-11-12",
        context_window=400_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["customizable-personality", "improved-instruction-following", "agentic-coding-via-codex-max"],
        one_line_summary="November 2025 refinement of GPT-5 focused on personality/steerability and coding/math consistency; still a likely late-2025-era source-model reference.",
        sources=["https://en.wikipedia.org/wiki/GPT-5.1"],
    ),
    ModelProfile(
        model_family="GPT-5",
        known_ids=["gpt-5", "gpt-5-2025-08-07", "gpt-5-chat-latest", "gpt-5-mini", "gpt-5-nano", "gpt-5-pro"],
        provider="openai",
        release_date="2025-08-07",
        context_window=400_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["strong-math-reasoning", "unified-reasoning-and-chat", "long-context"],
        one_line_summary="Unified OpenAI reasoning+chat line (Aug 2025); strong math/science benchmarks but one third-party agentic leaderboard flagged comparatively weaker structured tool-calling (59.2% vs GLM-4.5's 70.9%). Deprecating Dec 11, 2026.",
        sources=["https://openai.com/index/introducing-gpt-5/"],
    ),
    ModelProfile(
        model_family="GPT-4.1",
        known_ids=["gpt-4.1", "gpt-4.1-2025-04-14"],
        provider="openai",
        release_date="2025-04-14",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["long-context", "instruction-following", "agentic-tool-calling-reliability", "coding"],
        one_line_summary="Non-reasoning flagship tuned specifically for agentic tool-use and instruction-following fidelity (SWE-bench Verified 54.6%, +30% tool-calling efficiency vs GPT-4o).",
        sources=["https://openai.com/index/gpt-4-1/"],
    ),
    ModelProfile(
        model_family="GPT-4.1 mini",
        known_ids=["gpt-4.1-mini", "gpt-4.1-mini-2025-04-14"],
        provider="openai",
        release_date="2025-04-14",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "long-context", "vision"],
        one_line_summary="Cost-efficient mid-size GPT-4.1 family member -- good default for high-volume agent workflows where full GPT-4.1 is overkill.",
        sources=["https://openrouter.ai/openai/gpt-4.1-mini"],
    ),
    ModelProfile(
        model_family="GPT-4.1 nano",
        known_ids=["gpt-4.1-nano", "gpt-4.1-nano-2025-04-14"],
        provider="openai",
        release_date="2025-04-14",
        context_window=1_000_000,
        modality=["text", "vision"],
        reasoning_math_strength=2,
        coding_strength=2,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheapest-fastest-openai-model", "1M-context-at-tiny-cost"],
        one_line_summary="OpenAI's smallest/fastest/cheapest model -- long context at nano-scale cost, for simple/high-volume tasks rather than complex agentic reasoning.",
        sources=["https://pricepertoken.com/pricing-page/model/openai-gpt-4.1-nano"],
    ),
    ModelProfile(
        model_family="GPT-4o",
        known_ids=["gpt-4o", "gpt-4o-2024-05-13", "gpt-4o-2024-08-06", "gpt-4o-2024-11-20", "chatgpt-4o-latest"],
        provider="openai",
        release_date="2024-05-13",
        context_window=128_000,
        modality=["text", "vision", "audio"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["natively-multimodal", "battle-tested", "broad-ecosystem-support"],
        one_line_summary="Long-running 2024-era multimodal flagship, ChatGPT/API default for over a year (SWE-bench Verified 33.2%) -- extremely likely to still appear as a legacy source model.",
        sources=["https://openrouter.ai/openai/gpt-4o/benchmarks"],
    ),
    ModelProfile(
        model_family="GPT-4o mini",
        known_ids=["gpt-4o-mini", "gpt-4o-mini-2024-07-18"],
        provider="openai",
        release_date="2024-07-18",
        context_window=128_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=2,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "vision", "good-chat-for-price-tier"],
        one_line_summary="Cost-efficient small multimodal model from mid-2024 -- still widely referenced as a budget tier in older agent configs.",
        sources=["https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/"],
    ),
    ModelProfile(
        model_family="o1",
        known_ids=["o1", "o1-2024-12-17", "o1-preview", "o1-mini", "o1-pro"],
        provider="openai",
        release_date="2024-12-05",
        context_window=200_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["extended-reasoning", "math-science-problem-solving"],
        one_line_summary="OpenAI's first mainstream extended-reasoning model -- strong on deep math/logic but weak on tool-integrated agentic workflows vs later o-series. Deprecating in the Jul-Oct 2026 window.",
        sources=["https://en.wikipedia.org/wiki/OpenAI_o1"],
    ),
    ModelProfile(
        model_family="o3",
        known_ids=["o3", "o3-2025-04-16", "o3-pro", "o3-mini", "o3-deep-research"],
        provider="openai",
        release_date="2025-04-16",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["extended-reasoning", "sota-coding-math-at-release", "native-multi-tool-agentic-orchestration"],
        one_line_summary="Landmark reasoning model combining frontier math/coding (SWE-bench Verified 71.7%) with the first native multi-tool agentic orchestration in the o-series. Deprecating Dec 11, 2026.",
        sources=["https://openai.com/index/introducing-o3-and-o4-mini/"],
    ),
    ModelProfile(
        model_family="o4-mini",
        known_ids=["o4-mini", "o4-mini-2025-04-16", "o4-mini-high"],
        provider="openai",
        release_date="2025-04-16",
        context_window=200_000,
        modality=["text", "vision"],
        reasoning_math_strength=4,
        coding_strength=3,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap-reasoning-model", "strong-tool-augmented-math", "fast"],
        one_line_summary="Cost-efficient sibling to o3, released same day -- brings tool-integrated reasoning to a cheaper, faster tier.",
        sources=["https://en.wikipedia.org/wiki/OpenAI_o4-mini"],
    ),

    # ======================================================================
    # Google Gemini
    # ======================================================================
    ModelProfile(
        model_family="Gemini 3.6 Flash",
        known_ids=["gemini-3.6-flash", "models/gemini-3.6-flash"],
        provider="google",
        release_date="2026-07-21",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic", "computer-use", "fast", "token-efficient", "cheap-for-tier"],
        one_line_summary="Google's current general-purpose 'workhorse' -- best token efficiency and top computer-use/agentic scores in the family (OSWorld-Verified 83.0%, GDPval-AA v2 1421).",
        sources=["https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-6-flash-3-5-flash-lite-3-5-flash-cyber/"],
    ),
    ModelProfile(
        model_family="Gemini 3.1 Pro",
        known_ids=["gemini-3.1-pro-preview", "models/gemini-3.1-pro-preview", "gemini-3.1-pro-preview-customtools"],
        provider="google",
        release_date="2026-02-19",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["frontier-reasoning", "huge-context-window", "agentic-customtools-variant", "coding"],
        one_line_summary="Google's top-of-line reasoning/coding model while Gemini 3.5 Pro remains delayed (SWE-bench Verified 80.6%, tau2-Bench Telecom 99.3%, MCP Atlas 69.2%).",
        sources=["https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview"],
    ),
    ModelProfile(
        model_family="Gemini 3.5 Flash",
        known_ids=["gemini-3.5-flash", "models/gemini-3.5-flash"],
        provider="google",
        release_date="2026-05-19",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic", "coding", "fast", "cheaper-than-pro"],
        one_line_summary="Became the default Gemini-app model at launch -- a Flash-tier model that beat the previous Pro-tier model on Terminal-Bench (76.2% vs 70.3%) at ~40% lower cost.",
        sources=["https://www.marktechpost.com/2026/05/20/google-introduces-gemini-3-5-flash-at-i-o-2026-a-faster-and-cheaper-model-for-ai-agents-and-coding/"],
    ),
    ModelProfile(
        model_family="Gemini 3.5 Flash-Lite",
        known_ids=["gemini-3.5-flash-lite", "models/gemini-3.5-flash-lite"],
        provider="google",
        release_date="2026-07-21",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=3,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "fastest-in-class", "high-throughput", "agentic-search"],
        one_line_summary="Fastest/cheapest currently-GA Gemini 3.5-class model, built for high-volume low-latency agentic search and document processing.",
        sources=["https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-6-flash-3-5-flash-lite-3-5-flash-cyber/"],
    ),
    ModelProfile(
        model_family="Gemini 3.1 Flash-Lite",
        known_ids=["gemini-3.1-flash-lite", "models/gemini-3.1-flash-lite"],
        provider="google",
        release_date="2026-02",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "high-throughput", "low-latency"],
        one_line_summary="Cost-efficient, high-throughput Flash-Lite model, later superseded by Gemini 3.5 Flash-Lite.",
        sources=["https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite"],
    ),
    ModelProfile(
        model_family="Gemini 3 Pro",
        known_ids=["gemini-3-pro-preview", "models/gemini-3-pro-preview"],
        provider="google",
        release_date="2025-11-18",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["frontier-reasoning", "huge-context-window", "multimodal"],
        one_line_summary="Original Gemini 3 flagship (GPQA Diamond 91.9%, LMArena #1 at launch); now deprecated in favor of Gemini 3.1 Pro.",
        sources=["https://blog.google/products/gemini/gemini-3/"],
    ),
    ModelProfile(
        model_family="Gemini 3 Flash",
        known_ids=["gemini-3-flash-preview", "models/gemini-3-flash-preview"],
        provider="google",
        release_date="2025-12-17",
        context_window=1_048_576,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["cheap", "fast", "coding-for-cost", "agentic"],
        one_line_summary="Speed/cost-optimized model that briefly beat Gemini 3 Pro on SWE-bench Verified (78% vs 76.2%) at under 1/4 the cost.",
        sources=["https://ainativedev.io/news/with-gemini-3-flash-google-gives-developers-a-low-cost-model-built-for-speed"],
    ),
    ModelProfile(
        model_family="Gemini 2.5 Pro",
        known_ids=["gemini-2.5-pro", "models/gemini-2.5-pro"],
        provider="google",
        release_date="2025-03",
        context_window=1_000_000,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["huge-context-window", "multimodal", "reasoning"],
        one_line_summary="Frontier reasoning model with a very large context window; tau-bench numbers vary significantly by harness across sources (HAL: airline 52.8-71.8%), reflecting real measurement uncertainty rather than a single fixed score.",
        sources=["https://hal.cs.princeton.edu/reliability/agent/gemini-2-5-pro/"],
    ),
    ModelProfile(
        model_family="Gemini 2.5 Flash",
        known_ids=["gemini-2.5-flash", "models/gemini-2.5-flash"],
        provider="google",
        release_date="2025-04",
        context_window=1_000_000,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["huge-context-window", "cheap", "fast"],
        one_line_summary="Fast, cheap variant of Gemini 2.5 with the same large context window (HAL GAIA 46.7%, tau-bench airline 59.0% clean).",
        sources=["https://hal.cs.princeton.edu/reliability/agent/gemini-2-5-flash/"],
    ),
    ModelProfile(
        model_family="Gemini 2.0 Flash",
        known_ids=["gemini-2.0-flash", "gemini-2.0-flash-001", "models/gemini-2.0-flash"],
        provider="google",
        release_date="2025-02-05",
        context_window=1_000_000,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=3,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic-tool-use-design", "native-multimodal-generation"],
        one_line_summary="Built explicitly for 'the agentic era' (native tool use, code execution, search grounding). Retired 2026-06-01 -- not callable today; remap to Gemini 3.5/3.6 Flash.",
        sources=["https://ai.google.dev/gemini-api/docs/deprecations"],
    ),
    ModelProfile(
        model_family="Gemini 2.0 Flash-Lite",
        known_ids=["gemini-2.0-flash-lite", "gemini-2.0-flash-lite-001", "models/gemini-2.0-flash-lite"],
        provider="google",
        release_date="2025-02-25",
        context_window=1_000_000,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=2,
        coding_strength=2,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["ultra-low-cost", "high-throughput"],
        one_line_summary="Ultra-low-cost multimodal model. Retired 2026-06-01 -- not callable today; remap to Gemini 3.1/3.5 Flash-Lite.",
        sources=["https://ai.google.dev/gemini-api/docs/deprecations"],
    ),
    ModelProfile(
        model_family="Gemini 1.5 Pro",
        known_ids=["gemini-1.5-pro", "gemini-1.5-pro-001", "gemini-1.5-pro-002", "models/gemini-1.5-pro"],
        provider="google",
        release_date="2024-05",
        context_window=1_000_000,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["long-context (up to 2M)", "strong-multimodal-reasoning", "legacy"],
        one_line_summary="Google's 2024 flagship long-context model. Fully shut down September 2025 -- NOT callable today; source-only reference in any migration.",
        sources=["https://llm-stats.com/models/gemini-1.5-pro"],
    ),
    ModelProfile(
        model_family="Gemini 1.5 Flash",
        known_ids=["gemini-1.5-flash", "gemini-1.5-flash-001", "gemini-1.5-flash-002", "models/gemini-1.5-flash"],
        provider="google",
        release_date="2024-05",
        context_window=1_000_000,
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["fast-low-cost-multimodal", "legacy"],
        one_line_summary="Google's cost-optimized 1.5-gen workhorse. Fully shut down September 2025 -- NOT callable today; source-only reference.",
        sources=["https://llm-stats.com/models/gemini-1.5-flash"],
    ),
    ModelProfile(
        model_family="Gemini 1.0 Pro",
        known_ids=["gemini-1.0-pro", "gemini-pro", "models/gemini-pro"],
        provider="google",
        release_date="2023-12",
        context_window=32_760,
        modality=["text", "vision"],
        reasoning_math_strength=2,
        coding_strength=2,
        agentic_tool_use_strength=1,
        instruction_following_general_chat=2,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["legacy", "retired", "first-generation-gemini"],
        one_line_summary="The original December 2023 Gemini model. Retired -- not callable today; a common legacy source-id (bare 'gemini-pro').",
        sources=["https://ai.google.dev/gemini-api/docs/deprecations"],
    ),

    # ======================================================================
    # Open-weight
    # ======================================================================
    ModelProfile(
        model_family="gpt-oss-120b",
        known_ids=["gpt-oss-120b", "openai/gpt-oss-120b", "groq/openai/gpt-oss-120b", "bedrock/openai.gpt-oss-120b-1:0"],
        provider="openai",
        open_weight=True,
        release_date="2025-08",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["MoE-efficient", "reasoning", "tool-use-by-design", "single-80GB-GPU", "Apache-2.0"],
        one_line_summary="OpenAI's largest open-weight MoE model, near o4-mini on reasoning/coding (AIME 2024 95.8%, GPQA 80.1%); cheaply self-hostable or served on Groq/Bedrock/watsonx.",
        sources=["https://openai.com/index/gpt-oss-model-card/"],
    ),
    ModelProfile(
        model_family="gpt-oss-20b",
        known_ids=["gpt-oss-20b", "openai/gpt-oss-20b", "groq/openai/gpt-oss-20b"],
        provider="openai",
        open_weight=True,
        release_date="2025-08",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "runs-on-16GB-edge-hardware", "MoE-efficient", "same-tool-format-as-120b"],
        one_line_summary="OpenAI's small open-weight model for edge/low-cost deployment, roughly o3-mini-class (GPQA Diamond 58.6%).",
        sources=["https://huggingface.co/openai/gpt-oss-20b"],
    ),
    ModelProfile(
        model_family="DeepSeek V4-Pro / V4-Flash",
        known_ids=["deepseek-ai/DeepSeek-V4-Pro", "deepseek-ai/DeepSeek-V4-Flash", "deepseek-chat", "deepseek-reasoner"],
        provider="deepseek",
        open_weight=True,
        release_date="2026-04-24",
        context_window=1_000_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["1M-context-genuinely-usable-by-agents", "MoE-efficient", "leading-open-weight-swe-bench", "far-cheaper-than-closed-frontier"],
        one_line_summary="DeepSeek's April 2026 flagship pair (shipped instead of a standalone 'R2'), competitive with GPT-5/Gemini 3.1 Pro/Claude Opus 4.6 on reasoning/coding at a fraction of the cost (SWE-bench Verified ~80.6%, LiveCodeBench 93.5%).",
        sources=["https://huggingface.co/blog/deepseekv4"],
    ),
    ModelProfile(
        model_family="DeepSeek V3.2",
        known_ids=["deepseek-ai/DeepSeek-V3.2", "deepseek-ai/DeepSeek-V3.2-Exp", "deepseek.v3.2"],
        provider="deepseek",
        open_weight=True,
        release_date="2025-12",
        context_window=128_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["sparse-attention-cheap-long-context", "thinking-integrated-tool-use", "very-low-pricing"],
        one_line_summary="Introduced sparse attention and 'thinking-in-tool-use'; GPT-5-comparable general performance (SWE-bench Verified 67.8%, tau2-bench Telecom 96.2%).",
        sources=["https://arxiv.org/html/2512.02556v1"],
    ),
    ModelProfile(
        model_family="DeepSeek V3.1",
        known_ids=["deepseek-ai/DeepSeek-V3.1", "deepseek.v3-1"],
        provider="deepseek",
        open_weight=True,
        release_date="2025-08",
        context_window=128_000,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["hybrid-thinking-modes", "MoE-efficient", "improved-agentic-vs-R1"],
        one_line_summary="First DeepSeek 'hybrid reasoning' release merging the separate V3 (chat) and R1 (reasoner) lines into one selectable model.",
        sources=["https://api-docs.deepseek.com/news/news250821/"],
    ),
    ModelProfile(
        model_family="DeepSeek V3",
        known_ids=["deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepSeek-V3-0324", "deepseek-chat"],
        provider="deepseek",
        open_weight=True,
        release_date="2024-12",
        context_window=128_000,
        modality=["text"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "MoE-efficient", "long-context", "widely-mirrored-self-hostable"],
        one_line_summary="The original 671B MoE model that proved a Chinese lab could match GPT-4-class quality at a fraction of cost (MMLU 88.5%); not RL-trained for agentic tool-use.",
        sources=["https://arxiv.org/pdf/2412.19437"],
    ),
    ModelProfile(
        model_family="DeepSeek R1-0528",
        known_ids=["deepseek-ai/DeepSeek-R1-0528", "deepseek-reasoner"],
        provider="deepseek",
        open_weight=True,
        release_date="2025-05",
        context_window=128_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["reasoning", "math-competition-performance", "open-weights"],
        one_line_summary="Mid-2025 refresh of R1 closing much of the gap to o3 on AIME/GPQA (AIME 2025 87.5%); KNOWN WEAKNESS: unreliable structured tool-calling (tool calls sometimes emitted as text, not the tool_calls array) -- documented in multiple GitHub issues.",
        sources=["https://github.com/deepseek-ai/DeepSeek-R1/issues/9"],
    ),
    ModelProfile(
        model_family="DeepSeek R1",
        known_ids=["deepseek-ai/DeepSeek-R1", "deepseek-reasoner"],
        provider="deepseek",
        open_weight=True,
        release_date="2025-01",
        context_window=128_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=3,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["reasoning", "cheap-vs-o1-class", "MIT-licensed"],
        one_line_summary="The open-weight reasoning model that matched OpenAI o1 on math/coding in early 2025, triggering the 'DeepSeek moment'; same tool-calling reliability weakness as R1-0528.",
        sources=["https://arxiv.org/pdf/2501.12948"],
    ),
    ModelProfile(
        model_family="Kimi K2-Thinking",
        known_ids=["moonshotai/Kimi-K2-Thinking", "moonshot.kimi-k2-thinking"],
        provider="moonshot",
        open_weight=True,
        release_date="2025-11",
        context_window=262_144,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic", "long-horizon-tool-use (200-300 sequential calls)", "reasoning", "strong-coding"],
        one_line_summary="Moonshot's 'Thinking Agent' model -- end-to-end trained to interleave chain-of-thought with function calls, demonstrated stable agency across 200-300 consecutive tool invocations; independently evaluated by NIST CAISI.",
        sources=["https://huggingface.co/moonshotai/Kimi-K2-Thinking"],
    ),
    ModelProfile(
        model_family="Kimi K2.5",
        known_ids=["moonshotai/Kimi-K2.5", "moonshotai.kimi-k2.5"],
        provider="moonshot",
        open_weight=True,
        release_date="2026-01",
        context_window=262_144,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic", "vision", "multi-agent-orchestration (Agent Swarm)", "strong-coding"],
        one_line_summary="First natively multimodal K2 release, adding vision grounding and a built-in multi-agent task-decomposition feature ('Agent Swarm') to K2-Thinking's agentic design.",
        sources=["https://huggingface.co/moonshotai/Kimi-K2.5"],
    ),
    ModelProfile(
        model_family="Kimi K2",
        known_ids=["moonshotai/Kimi-K2-Instruct", "moonshotai/Kimi-K2-Instruct-0905", "groq/moonshotai/kimi-k2-instruct"],
        provider="moonshot",
        open_weight=True,
        release_date="2025-07",
        context_window=262_144,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic", "strong-coding", "tool-calling-first-design", "long-context", "MoE-efficient", "cheap-on-groq"],
        one_line_summary="Moonshot's flagship MoE model explicitly marketed and benchmarked around agentic tool-use (tau2 Retail 70.6, Telecom 65.8) -- a top open alternative for agent-orchestration platforms.",
        sources=["https://huggingface.co/moonshotai/Kimi-K2-Instruct"],
    ),
    ModelProfile(
        model_family="Qwen 3.5 397B-A17B",
        known_ids=["Qwen/Qwen3.5-397B-A17B"],
        provider="alibaba",
        open_weight=True,
        release_date="2026-02-16",
        context_window=1_000_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["newest-gen-flagship", "MoE-efficient", "very-long-context", "multilingual (201 langs)", "reasoning", "agentic"],
        one_line_summary="Alibaba's newest (Feb 2026) flagship, positioned for agentic use (GDPval-AA Elo 1221, +361 vs Qwen3-235B); not yet confirmed on managed catalogs like Groq/Bedrock/watsonx as of this research.",
        sources=["https://artificialanalysis.ai/articles/qwen3-5-397b-a17b-everything-you-need-to-know"],
    ),
    ModelProfile(
        model_family="Qwen 3 235B-A22B",
        known_ids=["Qwen/Qwen3-235B-A22B-Instruct-2507", "Qwen/Qwen3-235B-A22B-Thinking-2507", "qwen.qwen3-235b-a22b-2507-v1:0"],
        provider="alibaba",
        open_weight=True,
        release_date="2025-07",
        context_window=262_144,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["MoE-efficient", "frontier-open-weight-reasoning", "strong-coding", "long-context", "instruct-vs-thinking-variants"],
        one_line_summary="Qwen's flagship open-weight MoE model; the Thinking-2507 variant (AIME'25 92.3, GPQA 81.1) topped several open-model reasoning leaderboards; fully managed on Bedrock.",
        sources=["https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-qwen-qwen3-235b-a22b-2507.html"],
    ),
    ModelProfile(
        model_family="Qwen 3 Coder 30B-A3B",
        known_ids=["Qwen/Qwen3-Coder-30B-A3B-Instruct", "qwen/qwen3-coder-30b-a3b-instruct"],
        provider="alibaba",
        open_weight=True,
        release_date="2025-07",
        context_window=262_144,
        modality=["text"],
        reasoning_math_strength=2,
        coding_strength=4,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["MoE-efficient (30B/3B active)", "cheap-at-scale", "strong-agentic-tool-use-benchmark", "long-context"],
        one_line_summary="Highly efficient MoE model fine-tuned specifically for agentic coding/tool-use (BFCL-v2 76.6%); commonly deployed on Bedrock for cost-sensitive high-throughput agents.",
        sources=["https://openrouter.ai/qwen/qwen3-coder-30b-a3b-instruct"],
    ),
    ModelProfile(
        model_family="Qwen 3 32B",
        known_ids=["Qwen/Qwen3-32B", "qwen/qwen3-32b", "qwen.qwen3-32b-v1:0"],
        provider="alibaba",
        open_weight=True,
        release_date="2025-04-29",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["hybrid-thinking-mode", "top-tier-open-weight-tool-calling (BFCL)", "widely-available (Groq+Bedrock)"],
        one_line_summary="Widely-adopted mid-size dense flagship -- top-tier open-weight performer on the Berkeley Function-Calling Leaderboard (~75.7%), common default for enterprise agent-orchestration.",
        sources=["https://console.groq.com/docs/model/qwen/qwen3-32b"],
    ),
    ModelProfile(
        model_family="Qwen 2.5 72B Instruct",
        known_ids=["Qwen/Qwen2.5-72B-Instruct", "qwen2.5-72b-instruct"],
        provider="alibaba",
        open_weight=True,
        release_date="2024-09",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=3,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["dense-flagship-of-2.5-gen", "strong-general-reasoning", "long-context", "widely-self-hostable"],
        one_line_summary="The flagship Qwen2.5 dense model -- an open Llama-3.1-405B-class alternative widely used for enterprise self-hosting before Qwen3 arrived.",
        sources=["https://qwenlm.github.io/blog/qwen2.5/"],
    ),
    ModelProfile(
        model_family="Qwen 2.5 7B Instruct",
        known_ids=["Qwen/Qwen2.5-7B-Instruct", "qwen2.5-7b-instruct"],
        provider="alibaba",
        open_weight=True,
        release_date="2024-09",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=2,
        coding_strength=4,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "most-downloaded-qwen-model", "good-coding-for-size", "multilingual"],
        one_line_summary="The most widely downloaded Qwen open model on Hugging Face -- a cheap, fast 7B workhorse for lightweight chat, coding help, and edge/agent deployments.",
        sources=["https://qwenlm.github.io/blog/qwen2.5-llm/"],
    ),
    ModelProfile(
        model_family="Llama-3.1-Nemotron-70B-Instruct",
        known_ids=["nvidia/Llama-3.1-Nemotron-70B-Instruct", "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"],
        provider="nvidia",
        open_weight=True,
        release_date="2024-10",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=2,
        coding_strength=None,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["strong-chat-helpfulness-alignment", "beat-gpt4o-claude3.5-on-arena-hard-at-release", "long-context"],
        one_line_summary="NVIDIA's late-2024 helpfulness-RLHF'd Llama-3.1-70B derivative -- topped Arena Hard/AlpacaEval/MT-Bench at release; not tuned for math/coding/agentic tool-use, now superseded by Nemotron Super/Ultra/3.",
        sources=["https://huggingface.co/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"],
    ),
    ModelProfile(
        model_family="Llama-3.3-Nemotron-Super-49B",
        known_ids=["nvidia/Llama-3_3-Nemotron-Super-49B-v1", "nvidia/llama-3.3-nemotron-super-49b-v1.5"],
        provider="nvidia",
        open_weight=True,
        release_date="2025-03-18",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=3,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["agentic-tool-calling-tuned", "RAG-optimized", "toggleable-reasoning-mode", "single-GPU-deployable"],
        one_line_summary="NAS-compressed 49B derivative of Llama-3.3-70B, explicitly post-trained for RAG and tool-calling agentic workflows (BFCL V2 Live 73.7%) with a switchable reasoning mode; popular cost-efficient agent backend on Bedrock.",
        sources=["https://huggingface.co/nvidia/Llama-3_3-Nemotron-Super-49B-v1"],
    ),
    ModelProfile(
        model_family="Llama-3.1-Nemotron-Ultra-253B",
        known_ids=["nvidia/Llama-3_1-Nemotron-Ultra-253B-v1"],
        provider="nvidia",
        open_weight=True,
        release_date="2025-04-07",
        context_window=131_072,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["reasoning", "long-horizon-agentic", "RAG", "toggleable-reasoning-mode"],
        one_line_summary="253B flagship (NAS-distilled from Llama-3.1-405B), reported to match/beat DeepSeek R1 on several reasoning benchmarks at ~half the size (GPQA 76.0%, AIME25 72.5% with reasoning on); aging relative to the newer Nemotron 3 family.",
        sources=["https://venturebeat.com/ai/nvidias-new-llama-3-1-nemotron-ultra-outperforms-deepseek-r1-at-half-the-size"],
    ),
    ModelProfile(
        model_family="Nemotron 3 Nano",
        known_ids=["nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"],
        provider="nvidia",
        open_weight=True,
        release_date="2025-12-15",
        context_window=1_000_000,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=4,
        agentic_tool_use_strength=4,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "1M-context", "long-horizon-agentic", "hybrid-mamba-transformer-efficiency", "serverless-bedrock-ready"],
        one_line_summary="Efficient hybrid Mamba-Transformer MoE (31.6B total/3.6B active) with 1M-token context, explicitly built 'for Agentic Reasoning' (AIME25 89.1%, GPQA 73.0%) -- the low-cost entry tier of NVIDIA's new Nemotron 3 agentic family.",
        sources=["https://nvidianews.nvidia.com/news/nvidia-debuts-nemotron-3-family-of-open-models"],
    ),
    ModelProfile(
        model_family="Nemotron 3 Super",
        known_ids=["nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16"],
        provider="nvidia",
        open_weight=True,
        release_date="2026-03-11",
        context_window=1_000_000,
        modality=["text"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["reasoning", "strong-coding", "agentic-tool-use (tau2-bench tuned)", "long-context", "high-throughput-moe"],
        one_line_summary="120B (12B-active) hybrid MoE workhorse tier, purpose-built and benchmarked for agentic tool-use -- tau2-bench average 61.15 across Airline/Retail/Telecom, AIME25 90.2%, LiveCodeBench 81.2%.",
        sources=["https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16"],
    ),
    ModelProfile(
        model_family="Nemotron 3 Ultra",
        known_ids=["nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4"],
        provider="nvidia",
        open_weight=True,
        release_date="2026-06-04",
        context_window=1_000_000,
        modality=["text"],
        reasoning_math_strength=4,
        coding_strength=None,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["reasoning", "long-horizon-agentic", "1M-context", "highest-throughput-us-open-flagship"],
        one_line_summary="NVIDIA's June 2026 550B (55B-active) flagship, explicitly engineered for long-running autonomous coding/research agents; ranked by Artificial Analysis as the top US open-weight model as of mid-2026.",
        sources=["https://developer.nvidia.com/blog/nvidia-nemotron-3-ultra-powers-faster-more-efficient-reasoning-for-long-running-agents/"],
    ),
    ModelProfile(
        model_family="Gemma 4 31B",
        known_ids=["google/gemma-4-31b-it"],
        provider="google",
        open_weight=True,
        release_date="2026-04-02",
        context_window=256_000,
        modality=["text", "vision"],
        reasoning_math_strength=5,
        coding_strength=5,
        agentic_tool_use_strength=5,
        instruction_following_general_chat=5,
        cost_latency_tier=CostTier.FRONTIER,
        notable_strengths=["reasoning", "strong-coding", "agentic-tool-use (major leap over Gemma 3)", "long-context", "apache-2.0-license"],
        one_line_summary="Google's April 2026 flagship open-weight generation (GPQA Diamond 84.3%, LiveCodeBench 80.0%) -- notably, the FIRST Gemma generation with strong native tool-calling (tau2-bench jumped from Gemma 3's ~6.6% to ~86.4%), reversing Gemma's long-standing weak-tool-use reputation.",
        sources=["https://ai.google.dev/gemma/docs/core/model_card_4"],
    ),
    ModelProfile(
        model_family="Gemma 3 27B",
        known_ids=["google/gemma-3-27b-it"],
        provider="google",
        open_weight=True,
        release_date="2025-03",
        context_window=128_000,
        modality=["text", "vision"],
        reasoning_math_strength=3,
        coding_strength=3,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["long-context", "multilingual (140+ languages)", "vision", "strong-math"],
        one_line_summary="Flagship-of-generation open dense model (MATH 89.0%, HumanEval 87.8%) with 128K context and vision; tool-calling is prompt-engineered rather than natively structured (no dedicated tool-call token).",
        sources=["https://ai.google.dev/gemma/docs/core/model_card_3"],
    ),
    ModelProfile(
        model_family="Gemma 3 12B",
        known_ids=["google/gemma-3-12b-it"],
        provider="google",
        open_weight=True,
        release_date="2025-03",
        context_window=128_000,
        modality=["text", "vision"],
        reasoning_math_strength=2,
        coding_strength=2,
        agentic_tool_use_strength=2,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["balanced-size-performance", "vision", "long-context", "multilingual"],
        one_line_summary="Mid-size Gemma 3 variant with vision and 128K context, chosen when cost/latency matter more than the last few points of quality vs the 27B.",
        sources=["https://ai.google.dev/gemma/docs/core/model_card_3"],
    ),
    ModelProfile(
        model_family="Gemma 3 4B",
        known_ids=["google/gemma-3-4b-it"],
        provider="google",
        open_weight=True,
        release_date="2025-03",
        context_window=128_000,
        modality=["text", "vision"],
        reasoning_math_strength=1,
        coding_strength=1,
        agentic_tool_use_strength=1,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "small-fast", "vision", "edge-friendly", "long-context-for-size"],
        one_line_summary="Small 4B variant with vision and a surprisingly long 128K context for cheap/edge deployments; weakest of the Gemma 3 sizes on graduate reasoning and hard coding benchmarks.",
        sources=["https://ai.google.dev/gemma/docs/core/model_card_3"],
    ),
    ModelProfile(
        model_family="Gemma 3n (E2B/E4B)",
        known_ids=["google/gemma-3n-E4B-it", "google/gemma-3n-E2B-it"],
        provider="google",
        open_weight=True,
        release_date="2025-06-26",
        modality=["text", "vision", "audio", "video"],
        reasoning_math_strength=None,
        coding_strength=None,
        agentic_tool_use_strength=None,
        instruction_following_general_chat=4,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["on-device", "audio+video+image+text", "cheap", "mobile-first"],
        one_line_summary="Mobile/edge-first multimodal model matching much larger dense models on chat quality (first sub-10B model to exceed 1300 LMArena Elo) while running in 2-3GB RAM; not commonly seen in enterprise cloud orchestration alongside mainline Gemma 3.",
        sources=["https://developers.googleblog.com/en/introducing-gemma-3n/"],
    ),
    ModelProfile(
        model_family="Gemma 2 27B",
        known_ids=["google/gemma-2-27b-it"],
        provider="google",
        open_weight=True,
        release_date="2024-08",
        context_window=8_192,
        modality=["text"],
        reasoning_math_strength=2,
        coding_strength=2,
        agentic_tool_use_strength=1,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.MID,
        notable_strengths=["dense-efficient-27B", "distillation-trained", "superseded-by-gemma-3-4"],
        one_line_summary="Dense 27B open chat model, valued at release for strong Arena-style chat quality but limited by an 8K context window and no native tool-calling.",
        sources=["https://arxiv.org/pdf/2408.00118"],
    ),
    ModelProfile(
        model_family="Gemma 2 9B",
        known_ids=["google/gemma-2-9b-it"],
        provider="google",
        open_weight=True,
        release_date="2024-06",
        context_window=8_192,
        modality=["text"],
        reasoning_math_strength=2,
        coding_strength=1,
        agentic_tool_use_strength=1,
        instruction_following_general_chat=3,
        cost_latency_tier=CostTier.SMALL,
        notable_strengths=["cheap", "small-fast", "widely-hosted-historically"],
        one_line_summary="Small 9B chat model, historically popular on Groq for cheap/low-latency inference; since deprecated from Groq's current model list along with the rest of the Gemma 2 line.",
        sources=["https://localaimaster.com/models/gemma-2-9b"],
    ),
]
