"""Compile a `MappingSpec` into a pure Python adapter.

This is deliberately not a model's job. Every transform the translator can name
-- copy, rename, constant, enum translation, type coercion, join, array
collection -- has exactly one correct rendering in code, and generating it from
a template is reproducible, reviewable, and free. A model asked to write the
same function produces something plausible that differs between runs and has
to be tested to be believed.

So the split is: the model decides *what* maps to what (`translator.py`), and
this emits *how*. The model comes back only for the holes -- `DERIVE`
mappings, where the spec says "this needs real logic" and names it in prose --
and the Engineer patches those into the emitted skeleton. On a typical agent
schema that is a handful of functions rather than the whole adapter.

The generated module is stdlib-only and imports nothing at all. That is what
lets it run in a container with no packages installed, no network and no
filesystem, and it is also the property that makes the static guard cheap: an
adapter with no imports has a very small surface to check.

Two contracts the generated code upholds, both assertable and both tested:

  **A field with no source is omitted, not invented.** If every source path for
  a target is absent, the target key is not written. Null is a value; a missing
  field is a missing field, and conflating them is how a migration silently
  overwrites data on the target.

  The one deliberate exception is an IR field with *no mapping at all* -- no
  counterpart on the source platform, so no record will ever fill it. Those get
  their type's empty value on import, because the point of an intermediate
  representation is that one key means one thing everywhere, and a key that
  disappears on one platform and not another is not that. A field that is
  mapped but absent from this particular record still says absent: that is a
  gap in the data, and papering over it would deploy an agent named "".

  **It never raises.** Every read is guarded and every coercion falls back to
  omission. An adapter runs unattended over ten thousand records, and one that
  throws on record 4,001 halts the batch instead of flagging the record.
"""

from __future__ import annotations

from collections import Counter
from typing import Any

from agent_liftoff.foundry.types import (
    Direction,
    EntitySchema,
    FieldMapping,
    FieldNode,
    FlagReason,
    MappingSpec,
    TransformKind,
)

# Separator for JOIN. A space rather than anything cleverer because a joined
# result is nearly always prose destined for an instructions or description
# field, where a delimiter would read as markup.
JOIN_SEPARATOR = " "

# What "empty" means per JSON type, for filling unmapped IR fields. Absent
# entries are deliberate: `null` is not a type with an empty value, and a
# field whose type was never pinned down has no defensible filler.
_EMPTY_FOR_TYPE: dict[str, Any] = {
    "string": "",
    "array": [],
    "object": {},
    "boolean": False,
    "integer": 0,
    "number": 0,
}

# Transforms this module renders directly. Anything else becomes a hole for the
# Engineer, listed in the returned `derived` set so nothing is lost silently.
MECHANICAL = frozenset(
    {
        TransformKind.COPY,
        TransformKind.RENAME,
        TransformKind.CONSTANT,
        TransformKind.ENUM_MAP,
        TransformKind.COERCE,
        TransformKind.JOIN,
        TransformKind.COALESCE,
        TransformKind.COLLECT,
    }
)

PREAMBLE = '''"""Generated by the Agent Liftoff adapter foundry. Do not edit by hand.

Regenerating from the same MappingSpec produces identical output, so an edit
here is lost the next time the corridor is rebuilt. Change the spec instead.

  platform   {platform}
  direction  {direction}   ({direction_help})
  entity     {entity}
  schema     {fingerprint}
  generator  {generator}

Contract:
  transform(record) -> dict   maps one source record onto the target shape.
                              Pure. Never raises. Omits any target field whose
                              source was absent rather than writing a null.
  flags(record)     -> list   per-record review notes: fields present in this
                              record that could not be carried across.
"""

ADAPTER_META = {meta}

# Static review flags from the mapping spec: what this adapter cannot carry for
# any record. Per-record findings come from `flags()`.
REVIEW_FLAGS = {review_flags}

_MISSING = object()


def _get(record, path):
    """Read a dotted path. `[]` maps across an array rather than indexing it."""
    if not path:
        return record
    current = record
    for segment in path.split("."):
        collect = segment.endswith("[]")
        key = segment[:-2] if collect else segment
        if key:
            if isinstance(current, list):
                current = [i.get(key) for i in current if isinstance(i, dict)]
            elif isinstance(current, dict):
                if key not in current:
                    return _MISSING
                current = current[key]
            else:
                return _MISSING
        if collect:
            if not isinstance(current, list):
                return _MISSING
            flat = []
            for item in current:
                flat.extend(item) if isinstance(item, list) else flat.append(item)
            current = flat
    return current


def _put(target, path, value):
    """Write a dotted path, creating intermediate dicts."""
    parts = path.split(".")
    node = target
    for key in parts[:-1]:
        step = node.get(key)
        if not isinstance(step, dict):
            step = {{}}
            node[key] = step
        node = step
    node[parts[-1]] = value


def _text(value):
    """The faithful string for a value, or _MISSING when there isn't one."""
    if value is None:
        return _MISSING
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        parts = [_text(v) for v in value]
        kept = [p for p in parts if p is not _MISSING]
        return ", ".join(kept) if kept else _MISSING
    # A dict has no honest flat rendering; refusing beats emitting a repr.
    return _MISSING


def _number(value, want_int):
    if isinstance(value, bool) or value is None:
        return _MISSING
    if isinstance(value, (int, float)):
        return int(value) if want_int else float(value)
    if isinstance(value, str):
        try:
            return int(value.strip()) if want_int else float(value.strip())
        except ValueError:
            return _MISSING
    return _MISSING


def _boolean(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in ("true", "yes", "1", "on"):
            return True
        if lowered in ("false", "no", "0", "off"):
            return False
    if isinstance(value, (int, float)):
        return bool(value)
    return _MISSING


def _listed(value):
    if value is None:
        return _MISSING
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def _coerce(value, want):
    """Convert to the target's declared type, or _MISSING if it can't be done."""
    if want == "array":
        return _listed(value)
    if want == "string":
        return _text(value)
    if want == "integer":
        return _number(value, True)
    if want == "number":
        return _number(value, False)
    if want == "boolean":
        return _boolean(value)
    return value if value is not None else _MISSING
'''


def _literal(value: object) -> str:
    """Render a value as a Python literal.

    `repr` is safe for the value types a spec can hold -- pydantic has already
    constrained `constant` to str/int/float/bool/None and `enum_map` to
    str->str -- and it round-trips exactly, which a hand-rolled quoter would
    not for a string containing both quote characters.
    """
    return repr(value)


def array_prefix(path: str) -> str | None:
    """The array a path lives *inside*, e.g. `inputs[].name` -> `inputs[]`.

    A path that simply ends in `[]` (`tags[]`) is not inside an array, it *is*
    one, and is carried as a whole list rather than element-wise -- so this
    returns None for it.
    """
    head, marker, tail = path.rpartition("[]")
    if marker and tail.startswith("."):
        return head + marker
    return None


def _prefix_tokens(prefix: str | None) -> list[str]:
    """Words in an array prefix, for deciding which source array a group meant.

    Uses the aligner's tokeniser so `data.outputs[]` and `outputs[]` agree on
    `output` -- the same singularisation that makes `tools` match `tool`
    everywhere else.
    """
    from agent_liftoff.foundry.align import tokenize  # noqa: PLC0415 - avoids a cycle at import

    return tokenize((prefix or "").replace("[]", " "))


def container_path(path: str) -> str:
    """A settable path: `tags[]` addresses the list at `tags`."""
    return path[:-2] if path.endswith("[]") else path


def _relative(path: str, prefix: str) -> str:
    return path[len(prefix) :].lstrip(".")


def _single_level(prefix: str | None) -> bool:
    """Whether a prefix names exactly one array, at the top of its path.

    Element-wise generation is only emitted for one level of nesting.
    `topics[].nodes[].text` needs a nested loop to preserve grouping, and a
    single loop over the flattened reads would produce one long list where the
    target expects a list of lists -- so those become derived holes instead.
    """
    return bool(prefix) and prefix.count("[]") == 1 and prefix.endswith("[]")


def _target_type(node: FieldNode | None) -> str | None:
    """The single concrete type a target field wants, if it wants one.

    A field observed as both string and integer has no single answer, so no
    coercion is emitted and the value is carried as it stands -- which is the
    honest outcome, since the target evidently accepts both.
    """
    if node is None:
        return None
    concrete = [t for t in node.types if t != "null"]
    return concrete[0] if len(concrete) == 1 else None


def _derive_name(target_path: str) -> str:
    """A stable, valid function name for a derived target field."""
    cleaned = "".join(c if c.isalnum() else "_" for c in target_path)
    return f"_derive_{cleaned.strip('_').lower()}"


class _Emitter:
    """Renders one `MappingSpec`. Stateful only for the duration of a render."""

    def __init__(
        self,
        spec: MappingSpec,
        target_entity: EntitySchema | None,
        implementations: dict[str, str] | None = None,
    ) -> None:
        self.spec = spec
        self.targets = {n.path: n for n in (target_entity.fields if target_entity else [])}
        # target_path -> complete `def _derive_...(record):` source, supplied by
        # the Engineer for holes this module can't render. Written verbatim in
        # place of the stub, after the guard has checked it.
        self.implementations = implementations or {}
        self.lines: list[str] = []
        self.scalars: list[FieldMapping] = []
        self.arrays: dict[str, tuple[str, list[FieldMapping]]] = {}
        self.derived: list[FieldMapping] = []
        self._classify()

    # ------------------------------------------------------------------
    # Planning
    # ------------------------------------------------------------------

    def _classify(self) -> None:
        """Decide, once, what each mapping becomes: scalar, loop, or hole.

        Done up front rather than during rendering so the derived set is final
        before the stubs are written -- a group discovered to be non-renderable
        halfway through emitting would otherwise be stubbed after its call site
        had already been generated.
        """
        groups: dict[str, list[FieldMapping]] = {}
        for mapping in self.spec.mappings:
            if mapping.transform not in MECHANICAL:
                self.derived.append(mapping)
                continue
            prefix = array_prefix(mapping.target_path)
            if prefix is None:
                self.scalars.append(mapping)
            else:
                groups.setdefault(prefix, []).append(mapping)

        for prefix, mappings in groups.items():
            # Which source array the group is *mostly* drawn from. When one
            # mapping disagrees -- `outputs[].description` pointing at
            # `inputs[]` -- taking the whole group to a hand-written hole would
            # cost the four correct mappings to punish the one wrong one. The
            # majority is rendered; the dissenters become holes on their own.
            counts = Counter(
                array_prefix(path) for m in mappings for path in m.source_paths
            ).most_common(2)
            # A strict majority wins outright. On a tie, the name decides:
            # `outputs[]` fed by both `data.outputs[]` and `data.inputs[]` is a
            # cross-wire, and the array that shares a word with the target is
            # the one that meant it. Only if neither shares a word is there
            # genuinely nothing to choose between -- and a coin flip compiled
            # into a loop that runs over every record is the one thing this
            # module must never emit, so that case becomes a hole.
            source_prefix = None
            if counts and (len(counts) == 1 or counts[0][1] > counts[1][1]):
                source_prefix = counts[0][0]
            elif counts:
                wanted = set(_prefix_tokens(prefix))
                agreeing_names = [
                    candidate
                    for candidate, _ in counts
                    if candidate and wanted & set(_prefix_tokens(candidate))
                ]
                if len(agreeing_names) == 1:
                    source_prefix = agreeing_names[0]
            agreeing = [
                m
                for m in mappings
                if {array_prefix(p) for p in m.source_paths} == {source_prefix}
            ]
            renderable = (
                _single_level(prefix)
                and _single_level(source_prefix)
                and "[]" not in container_path(prefix)
            )
            if renderable and source_prefix and agreeing:
                self.arrays[prefix] = (source_prefix, agreeing)
                self.derived.extend(m for m in mappings if m not in agreeing)
            else:
                # Either the nesting is deeper than one level, or no source
                # array commands a majority. Both need real logic.
                self.derived.extend(mappings)

        self.scalars.sort(key=lambda m: m.target_path)
        self.derived = _dedupe(self.derived)

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def write(self, line: str = "") -> None:
        self.lines.append(line)

    def emit_read(self, mapping: FieldMapping, base: str, strip: str = "") -> list[str]:
        """The read side of one mapping, as lines at one indent level.

        Returned rather than written so the caller can re-indent them into a
        loop body without this method having to know where it is being placed.
        """
        out: list[str] = []
        if mapping.transform is TransformKind.CONSTANT:
            out.append(f"    _v = {_literal(mapping.constant)}")
            return out

        paths = [_relative(p, strip) if strip else p for p in mapping.source_paths]

        if mapping.transform is TransformKind.JOIN:
            out.append("    _parts = []")
            for path in paths:
                out.append(f"    _p = _text(_get({base}, {_literal(path)}))")
                out.append("    if _p is not _MISSING and _p != '':")
                out.append("        _parts.append(_p)")
            out.append(f"    _v = {_literal(JOIN_SEPARATOR)}.join(_parts) if _parts else _MISSING")
            return out

        if mapping.transform is TransformKind.COALESCE:
            # First source that is actually present wins. This is the transform
            # for a corpus assembled from more than one shape of the same
            # thing -- a solution export and a live API both describe an agent,
            # and they put its name in different places. A single-source
            # mapping there is not wrong for some records, it is right for one
            # source and absent for every other.
            out.append("    _v = _MISSING")
            for path in paths:
                out.append("    if _v is _MISSING or _v is None or _v == '':")
                out.append(f"        _c = _get({base}, {_literal(path)})")
                out.append("        if _c is not _MISSING:")
                out.append("            _v = _c")
            return out

        source = paths[0] if paths else ""
        out.append(f"    _v = _get({base}, {_literal(source)})")

        if mapping.transform is TransformKind.ENUM_MAP:
            out.append("    if _v is not _MISSING:")
            out.append(f"        _v = {_literal(mapping.enum_map)}.get(_text(_v), _MISSING)")
            return out

        want = _target_type(self.targets.get(mapping.target_path))
        if mapping.transform is TransformKind.COERCE and want:
            out.append("    if _v is not _MISSING:")
            out.append(f"        _v = _coerce(_v, {_literal(want)})")
        return out

    def emit_scalar(self, mapping: FieldMapping) -> None:
        target = container_path(mapping.target_path)
        sources = ", ".join(mapping.source_paths) or "(constant)"
        self.write(
            f"    # {target} <- {sources}  "
            f"[{mapping.transform.value}, confidence {mapping.confidence:.2f}]"
        )
        for line in self.emit_read(mapping, "record"):
            self.write(line)
        self.write("    if _v is not _MISSING and _v is not None:")
        self.write(f"        _put(out, {_literal(target)}, _v)")
        if mapping.default is not None:
            self.write("    else:")
            self.write(f"        _put(out, {_literal(target)}, {_literal(mapping.default)})")
        self.write()

    def emit_array(self, prefix: str, source_prefix: str, mappings: list[FieldMapping]) -> None:
        """A loop populating one target array from one source array."""
        target = container_path(prefix)
        self.write(f"    # {target}[] <- {source_prefix}  [collect, {len(mappings)} field(s)]")
        self.write(f"    _items = _get(record, {_literal(source_prefix)})")
        self.write("    if isinstance(_items, list):")
        self.write("        _rows = []")
        self.write("        for _item in _items:")
        self.write("            _row = {}")
        for mapping in sorted(mappings, key=lambda m: m.target_path):
            relative = container_path(_relative(mapping.target_path, prefix))
            for line in self.emit_read(mapping, "_item", strip=source_prefix):
                # emit_read renders at one indent; the loop body is at three.
                self.write("        " + line if line.strip() else "")
            self.write("            if _v is not _MISSING and _v is not None:")
            self.write(f"                _put(_row, {_literal(relative)}, _v)")
        self.write("            _rows.append(_row)")
        self.write(f"        _put(out, {_literal(target)}, _rows)")
        self.write()

    def emit_derived_stubs(self) -> None:
        """One function per unimplemented mapping, raising until it is written.

        A stub that raises is the point. It fails the generated tests loudly,
        which is what drives the Engineer's repair loop; a stub returning None
        would produce an adapter that passes and silently drops the field.
        """
        for mapping in self.derived:
            name = _derive_name(mapping.target_path)
            supplied = self.implementations.get(mapping.target_path)
            if supplied:
                self.write(f"# Written by the Engineer for `{mapping.target_path}`.")
                for line in supplied.rstrip().splitlines():
                    self.write(line)
                self.write()
                self.write()
                continue
            sources = ", ".join(mapping.source_paths) or "the whole record"
            self.write(f"def {name}(record):")
            self.write(f'    """Derive `{mapping.target_path}` from {sources}.')
            self.write()
            reason = mapping.rationale or "The mapping spec marked this as needing logic."
            self.write(f"    {' '.join(reason.split())}")
            self.write()
            self.write("    Return the value, or _MISSING to omit the field.")
            self.write('    """')
            self.write(f"    raise NotImplementedError({_literal(mapping.target_path)})")
            self.write()
            self.write()

    def emit_fill(self) -> None:
        """Give every unfilled IR field its type's empty value.

        The point of an intermediate representation is that one key means one
        thing whatever platform it came from, and a field that simply vanishes
        when the source lacks it breaks that: downstream code has to ask
        whether `web_search` is absent because the platform has no such notion
        or because this agent had it off. Writing `""` / `[]` / `false` says
        "known, and empty", which is the answer.

        Import only. On the way *out* of the IR the same trick would be
        actively harmful -- a create call reads an empty string as "set this
        field to empty", so filling ninety unmapped columns would overwrite the
        target's own defaults with blanks. Out there, absent means absent.

        Two exclusions, both to avoid the very error this is meant to prevent:
        a field with a closed vocabulary, where `""` is not one of the allowed
        values, and a field whose type the probe never pinned down.
        """
        if self.spec.direction is not Direction.IMPORT:
            return
        mapped = {container_path(m.target_path) for m in self.spec.mappings}
        fillable: list[tuple[str, Any]] = []
        for node in self.targets.values():
            path = container_path(node.path)
            if node.container or "[]" in node.path or path in mapped:
                continue
            if node.enum:
                continue
            empty = _EMPTY_FOR_TYPE.get(_target_type(node) or "")
            if empty is not None:
                fillable.append((path, empty))

        if not fillable:
            return
        self.write("    # Unfilled IR fields, set to their type's empty value so that one")
        self.write("    # key means one thing whatever platform the record came from.")
        for path, empty in sorted(fillable):
            self.write(f"    if _get(out, {_literal(path)}) is _MISSING:")
            self.write(f"        _put(out, {_literal(path)}, {_literal(empty)})")
        self.write()

    def emit_transform(self) -> None:
        self.write("def transform(record):")
        self.write('    """Map one source record onto the target shape."""')
        self.write("    if not isinstance(record, dict):")
        self.write("        return {}")
        self.write("    out = {}")
        self.write()
        for mapping in self.scalars:
            self.emit_scalar(mapping)
        for prefix in sorted(self.arrays):
            source_prefix, mappings = self.arrays[prefix]
            self.emit_array(prefix, source_prefix, mappings)
        for mapping in self.derived:
            target = container_path(mapping.target_path)
            self.write(f"    # {target} <- derived")
            self.write("    try:")
            self.write(f"        _v = {_derive_name(mapping.target_path)}(record)")
            self.write("    except Exception:")
            # A derived helper that raises costs its own field, not the record.
            self.write("        _v = _MISSING")
            self.write("    if _v is not _MISSING and _v is not None:")
            self.write(f"        _put(out, {_literal(target)}, _v)")
            self.write()
        self.emit_fill()
        self.write("    return out")
        self.write()
        self.write()

    def emit_flags(self) -> None:
        runtime = [
            flag
            for flag in self.spec.flags
            if flag.reason in (FlagReason.LOSSY, FlagReason.REQUIRES_AUTH)
            and flag.severity in ("warn", "block")
        ]
        self.write("def flags(record):")
        self.write('    """Review notes for this specific record."""')
        self.write("    found = []")
        self.write("    if not isinstance(record, dict):")
        self.write("        return found")
        for flag in runtime:
            self.write(f"    _v = _get(record, {_literal(flag.path)})")
            self.write("    if _v is not _MISSING and _v not in (None, '', [], {}):")
            self.write("        found.append({")
            self.write(f"            'path': {_literal(flag.path)},")
            self.write(f"            'reason': {_literal(flag.reason.value)},")
            self.write(f"            'detail': {_literal(' '.join(flag.detail.split()))},")
            self.write(f"            'severity': {_literal(flag.severity)},")
            self.write("        })")
        self.write("    return found")


def _dedupe(mappings: list[FieldMapping]) -> list[FieldMapping]:
    seen: set[str] = set()
    unique: list[FieldMapping] = []
    for mapping in mappings:
        if mapping.target_path in seen:
            continue
        seen.add(mapping.target_path)
        unique.append(mapping)
    unique.sort(key=lambda m: m.target_path)
    return unique


def emit_adapter(
    spec: MappingSpec,
    target_entity: EntitySchema | None = None,
    implementations: dict[str, str] | None = None,
) -> tuple[str, list[FieldMapping]]:
    """Render `spec` as a Python module.

    Returns the source and the mappings it could not render mechanically -- the
    holes. An empty second element means the adapter is complete with no model
    involvement at all, which is the common case and the one worth optimising
    for. `implementations` supplies bodies for those holes; any hole without
    one gets a stub that raises, so the gap shows up as a test failure rather
    than as a silently dropped field.
    """
    emitter = _Emitter(spec, target_entity, implementations)

    direction_help = (
        "platform record -> Agent Liftoff IR"
        if spec.direction.value == "import"
        else "Agent Liftoff IR -> platform record"
    )
    header = PREAMBLE.format(
        platform=spec.platform,
        direction=spec.direction.value,
        direction_help=direction_help,
        entity=spec.entity_kind.value,
        fingerprint=spec.schema_fingerprint[:16],
        generator=spec.generator,
        meta=_literal(
            {
                "platform": spec.platform,
                "direction": spec.direction.value,
                "entity_kind": spec.entity_kind.value,
                "schema_fingerprint": spec.schema_fingerprint,
                "ir_version": spec.ir_version,
                "spec_version": spec.spec_version,
                "mappings": len(spec.mappings),
            }
        ),
        review_flags=_literal(
            [
                {
                    "path": flag.path,
                    "reason": flag.reason.value,
                    "detail": " ".join(flag.detail.split()),
                    "severity": flag.severity,
                }
                for flag in spec.flags
            ]
        ),
    )

    emitter.write()
    emitter.write()
    emitter.emit_derived_stubs()
    emitter.emit_transform()
    emitter.emit_flags()
    return header + "\n".join(emitter.lines).rstrip() + "\n", list(emitter.derived)
