"""Generated by the Wheatear adapter foundry. Do not edit by hand.

Regenerating from the same MappingSpec produces identical output, so an edit
here is lost the next time the corridor is rebuilt. Change the spec instead.

  platform   copilot-studio
  direction  import   (platform record -> Wheatear IR)
  entity     connection
  schema     435c6a63ad313e79
  generator  deterministic

Contract:
  transform(record) -> dict   maps one source record onto the target shape.
                              Pure. Never raises. Omits any target field whose
                              source was absent rather than writing a null.
  flags(record)     -> list   per-record review notes: fields present in this
                              record that could not be carried across.
"""

ADAPTER_META = {'platform': 'copilot-studio', 'direction': 'import', 'entity_kind': 'connection', 'schema_fingerprint': '435c6a63ad313e79bc075911843ae62aae99ff0a3dd3da71d486c7785961877c', 'ir_version': 'wheatear/v1', 'spec_version': 'wheatear.foundry/v1', 'mappings': 0}

# Static review flags from the mapping spec: what this adapter cannot carry for
# any record. Per-record findings come from `flags()`.
REVIEW_FLAGS = [{'path': 'auth_type', 'reason': 'no_target_equivalent', 'detail': 'No source field produces `auth_type`; it will be left at its default.', 'severity': 'block'}, {'path': 'ref', 'reason': 'no_target_equivalent', 'detail': 'No source field produces `ref`; it will be left at its default.', 'severity': 'block'}, {'path': 'review_required', 'reason': 'no_target_equivalent', 'detail': 'No source field produces `review_required`; it will be left at its default.', 'severity': 'info'}, {'path': 'source_ref', 'reason': 'no_target_equivalent', 'detail': 'No source field produces `source_ref`; it will be left at its default.', 'severity': 'info'}, {'path': 'botcomponent_connectionreference[].@botcomponentid.schemaname', 'reason': 'lossy', 'detail': '`botcomponent_connectionreference[].@botcomponentid.schemaname` has no counterpart on the target and is dropped.', 'severity': 'warn'}, {'path': 'botcomponent_connectionreference[].@connectionreferenceid.connectionreferencelogicalname', 'reason': 'lossy', 'detail': '`botcomponent_connectionreference[].@connectionreferenceid.connectionreferencelogicalname` has no counterpart on the target and is dropped.', 'severity': 'warn'}, {'path': 'botcomponent_connectionreference[].iscustomizable', 'reason': 'lossy', 'detail': '`botcomponent_connectionreference[].iscustomizable` has no counterpart on the target and is dropped.', 'severity': 'warn'}]

_MISSING = object()


def _get(record, path):
    """Read a dotted path. `[]` maps across an array rather than indexing it."""
    if not path:
        return record
    current = record
    for segment in path.split("."):
        collect = segment.endswith("[]")
        key = segment[:-2] if collect else segment
        if key:
            if isinstance(current, list):
                current = [i.get(key) for i in current if isinstance(i, dict)]
            elif isinstance(current, dict):
                if key not in current:
                    return _MISSING
                current = current[key]
            else:
                return _MISSING
        if collect:
            if not isinstance(current, list):
                return _MISSING
            flat = []
            for item in current:
                flat.extend(item) if isinstance(item, list) else flat.append(item)
            current = flat
    return current


def _put(target, path, value):
    """Write a dotted path, creating intermediate dicts."""
    parts = path.split(".")
    node = target
    for key in parts[:-1]:
        step = node.get(key)
        if not isinstance(step, dict):
            step = {}
            node[key] = step
        node = step
    node[parts[-1]] = value


def _text(value):
    """The faithful string for a value, or _MISSING when there isn't one."""
    if value is None:
        return _MISSING
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        parts = [_text(v) for v in value]
        kept = [p for p in parts if p is not _MISSING]
        return ", ".join(kept) if kept else _MISSING
    # A dict has no honest flat rendering; refusing beats emitting a repr.
    return _MISSING


def _number(value, want_int):
    if isinstance(value, bool) or value is None:
        return _MISSING
    if isinstance(value, (int, float)):
        return int(value) if want_int else float(value)
    if isinstance(value, str):
        try:
            return int(value.strip()) if want_int else float(value.strip())
        except ValueError:
            return _MISSING
    return _MISSING


def _boolean(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in ("true", "yes", "1", "on"):
            return True
        if lowered in ("false", "no", "0", "off"):
            return False
    if isinstance(value, (int, float)):
        return bool(value)
    return _MISSING


def _listed(value):
    if value is None:
        return _MISSING
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def _coerce(value, want):
    """Convert to the target's declared type, or _MISSING if it can't be done."""
    if want == "array":
        return _listed(value)
    if want == "string":
        return _text(value)
    if want == "integer":
        return _number(value, True)
    if want == "number":
        return _number(value, False)
    if want == "boolean":
        return _boolean(value)
    return value if value is not None else _MISSING


def transform(record):
    """Map one source record onto the target shape."""
    if not isinstance(record, dict):
        return {}
    out = {}

    # Unfilled IR fields, set to their type's empty value so that one
    # key means one thing whatever platform the record came from.
    if _get(out, 'auth_type') is _MISSING:
        _put(out, 'auth_type', '')
    if _get(out, 'ref') is _MISSING:
        _put(out, 'ref', '')
    if _get(out, 'review_required') is _MISSING:
        _put(out, 'review_required', False)
    if _get(out, 'source_ref') is _MISSING:
        _put(out, 'source_ref', '')

    return out


def flags(record):
    """Review notes for this specific record."""
    found = []
    if not isinstance(record, dict):
        return found
    _v = _get(record, 'botcomponent_connectionreference[].@botcomponentid.schemaname')
    if _v is not _MISSING and _v not in (None, '', [], {}):
        found.append({
            'path': 'botcomponent_connectionreference[].@botcomponentid.schemaname',
            'reason': 'lossy',
            'detail': '`botcomponent_connectionreference[].@botcomponentid.schemaname` has no counterpart on the target and is dropped.',
            'severity': 'warn',
        })
    _v = _get(record, 'botcomponent_connectionreference[].@connectionreferenceid.connectionreferencelogicalname')
    if _v is not _MISSING and _v not in (None, '', [], {}):
        found.append({
            'path': 'botcomponent_connectionreference[].@connectionreferenceid.connectionreferencelogicalname',
            'reason': 'lossy',
            'detail': '`botcomponent_connectionreference[].@connectionreferenceid.connectionreferencelogicalname` has no counterpart on the target and is dropped.',
            'severity': 'warn',
        })
    _v = _get(record, 'botcomponent_connectionreference[].iscustomizable')
    if _v is not _MISSING and _v not in (None, '', [], {}):
        found.append({
            'path': 'botcomponent_connectionreference[].iscustomizable',
            'reason': 'lossy',
            'detail': '`botcomponent_connectionreference[].iscustomizable` has no counterpart on the target and is dropped.',
            'severity': 'warn',
        })
    return found
